name: Parent Workflow

on: 
  workflow_run:
    workflows: ["child-workflow"]
    types:
      - completed

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Manual Actions
        run: echo "Manual actions should be initialized here..."
        
      - name: Trigger Child Workflow
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
